### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Positive2022** [LegendaryEmoji/srod-v2#4]
https://github.com/LegendaryEmoji/srod-v2/blob/78ca452dba20f2c45927a60fdc673f4654a6a9d8/Src/Main.js#L340

Animals should be replaced with Anime

**Comment by LegendaryEmoji** [comment]
yes **great**, thanks

**Comment by LegendaryEmoji** [comment]
also, you have to wait for next update because it's going to change almost everything lol
